In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [2]:
dataset=pd.read_csv("Social_Network_Ads.csv")
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [4]:
dataset=dataset.drop("User ID",axis=1)
dataset

Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [5]:
dataset.columns

Index(['Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [6]:
indep=dataset[['Age', 'EstimatedSalary','Gender_Male']]
indep

Age  EstimatedSalary  Gender_Male
0     19            19000            1
1     35            20000            1
2     26            43000            0
3     27            57000            0
4     19            76000            1
..   ...              ...          ...
395   46            41000            0
396   51            23000            1
397   50            20000            0
398   36            33000            1
399   49            36000            0

[400 rows x 3 columns]

In [7]:
dep=dataset[['Purchased']]
dep

Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [8]:
dataset["Purchased"].value_counts()

0    257
1    143
Name: Purchased, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep,dep,test_size=1/3,random_state=0)
x_train,x_test,y_train,y_test


(     Age  EstimatedSalary  Gender_Male
 218   46            96000            0
 101   28            59000            1
 311   39            96000            1
 194   28            89000            1
 326   41            72000            1
 ..   ...              ...          ...
 323   48            30000            0
 192   29            43000            1
 117   36            52000            1
 47    27            54000            0
 172   26           118000            0
 
 [266 rows x 3 columns],      Age  EstimatedSalary  Gender_Male
 132   30            87000            1
 309   38            50000            0
 341   35            75000            1
 196   30            79000            0
 246   35            50000            0
 ..   ...              ...          ...
 168   29           148000            1
 150   26            15000            0
 393   60            42000            1
 66    24            19000            1
 240   42           149000            1
 
 [134 rows x

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [11]:
x_train,x_test

(array([[ 0.81203707,  0.7926083 , -0.99250926],
        [-0.96332069, -0.30625786,  1.00754728],
        [ 0.12162016,  0.7926083 ,  1.00754728],
        [-0.96332069,  0.5847147 ,  1.00754728],
        [ 0.31888214,  0.07983025,  1.00754728],
        [ 0.71340608, -1.28632769,  1.00754728],
        [-0.47016576, -0.00926701, -0.99250926],
        [-1.75236858,  0.3768211 , -0.99250926],
        [-0.66742773,  0.13922842,  1.00754728],
        [ 0.41751312,  0.31742293,  1.00754728],
        [-0.27290378,  0.07983025, -0.99250926],
        [-0.47016576,  2.36665983, -0.99250926],
        [ 0.22025115,  0.05013116,  1.00754728],
        [ 1.30519201,  2.27756258, -0.99250926],
        [ 0.81203707,  0.28772385,  1.00754728],
        [-0.27290378,  0.16892751,  1.00754728],
        [ 0.02298918, -0.54385055,  1.00754728],
        [-0.1742728 ,  0.16892751, -0.99250926],
        [-0.07564181,  0.25802476, -0.99250926],
        [ 0.02298918, -0.24685969,  1.00754728],
        [ 2.19287089

In [12]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
param_grid={'criterion':['gini','entropy'],
           'max_features':['auto','sqtr','log2'],
           'n_estimators':[10,100]}
grid=GridSearchCV(RandomForestClassifier(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid.fit(x_train,y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits


C:\Users\PC\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
20 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\PC\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\PC\Anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 467, in fit
    for i, t in enumerate(trees)
  File "C:\Users\PC\Anaconda3\lib\site-packages\joblib\parallel.py", line 921, in __call__
    if self.dispatch_one_batch(iterator):
  File "C:\Users\PC\Anaconda3\lib\site-packages\joblib\

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqtr', 'log2'],
                         'n_estimators': [10, 100]},
             scoring='f1_weighted', verbose=3)

In [13]:
re=grid.cv_results_
grid_predictions=grid.predict(x_test)
grid_predictions


array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1], dtype=int64)

In [14]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_predictions)
print("Confusion Matrix:\n",cm)

Confusion Matrix:
 [[79  6]
 [ 6 43]]


In [15]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_predictions)
print("classification_report:\n",clf_report)

classification_report:
               precision    recall  f1-score   support

           0       0.93      0.93      0.93        85
           1       0.88      0.88      0.88        49

    accuracy                           0.91       134
   macro avg       0.90      0.90      0.90       134
weighted avg       0.91      0.91      0.91       134



In [16]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter{}:\n".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter{'criterion': 'entropy', 'max_features': 'auto', 'n_estimators': 100}:
 0.9104477611940298


In [17]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

0.9603841536614646

In [18]:
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.031246  1.027626e-05         0.009378        0.007657   
1        0.143475  2.059476e-02         0.018223        0.006590   
2        0.015623  4.079676e-06         0.000000        0.000000   
3        0.071865  1.250392e-02         0.000000        0.000000   
4        0.028123  6.250936e-03         0.000000        0.000000   
5        0.149947  7.657192e-03         0.021873        0.007654   
6        0.031242  4.422006e-07         0.000000        0.000000   
7        0.165585  7.653313e-03         0.016139        0.001037   
8        0.015617  7.484065e-06         0.000000        0.000000   
9        0.078106  9.880007e-03         0.000000        0.000000   
10       0.021867  7.655163e-03         0.003124        0.006248   
11       0.088364  8.374323e-03         0.009373        0.007653   

   param_criterion param_max_features param_n_estimators  \
0             gini               auto                 10   
1             gini               auto                100   
2             gini               sqtr                 10   
3             gini               sqtr                100   
4             gini               log2                 10   
5             gini               log2                100   
6          entropy               auto                 10   
7          entropy               auto                100   
8          entropy               sqtr                 10   
9          entropy               sqtr                100   
10         entropy               log2                 10   
11         entropy               log2                100   

                                               params  split0_test_score  \
0   {'criterion': 'gini', 'max_features': 'auto', ...           0.885356   
1   {'criterion': 'gini', 'max_features': 'auto', ...           0.847141   
2   {'criterion': 'gini', 'max_features': 'sqtr', ...                NaN   
3   {'criterion': 'gini', 'max_features': 'sqtr', ...                NaN   
4   {'criterion': 'gini', 'max_features': 'log2', ...           0.826263   
5   {'criterion': 'gini', 'max_features': 'log2', ...           0.867478   
6   {'criterion': 'entropy', 'max_features': 'auto...           0.867478   
7   {'criterion': 'entropy', 'max_features': 'auto...           0.867478   
8   {'criterion': 'entropy', 'max_features': 'sqtr...                NaN   
9   {'criterion': 'entropy', 'max_features': 'sqtr...                NaN   
10  {'criterion': 'entropy', 'max_features': 'log2...           0.867478   
11  {'criterion': 'entropy', 'max_features': 'log2...           0.847141   

    split1_test_score  split2_test_score  split3_test_score  \
0            0.850809           0.851527           0.925272   
1            0.888107           0.851527           0.925272   
2                 NaN                NaN                NaN   
3                 NaN                NaN                NaN   
4            0.850809           0.832483           0.925272   
5            0.868752           0.851527           0.944161   
6            0.850809           0.870362           0.925272   
7            0.907177           0.851527           0.944161   
8                 NaN                NaN                NaN   
9                 NaN                NaN                NaN   
10           0.831253           0.814409           0.925272   
11           0.888107           0.851527           0.925272   

    split4_test_score  mean_test_score  std_test_score  rank_test_score  
0            0.923510         0.887295        0.032766                5  
1            0.943699         0.891149        0.038579                3  
2                 NaN              NaN             NaN                9  
3                 NaN              NaN             NaN               10  
4            0.943699         0.875705        0.049016                8  
5            0.962264         0.898837        0.045175                2  
6          

In [19]:
print(grid.best_params_)

{'criterion': 'entropy', 'max_features': 'auto', 'n_estimators': 100}


In [20]:
age_input=float(input('Age input:'))
Salary_input=float(input('Salary:'))
gender_male_input=int(input("gender male 0 or 1:")


Age input:40
Salary:100000
gender male 0 or 1:0


In [21]:
Future_prediction=grid.predict([[age_input,Salary_input,gender_male_input]])
print("Future_Prediction={}".format(Future_prediction))

Future_Prediction=[1]
