In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [2]:
dataset=pd.read_csv("Social_Network_Ads.csv")
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [4]:
dataset=dataset.drop("User ID",axis=1)
dataset

Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [5]:
dataset.columns

Index(['Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [6]:
indep=dataset[['Age', 'EstimatedSalary','Gender_Male']]
indep

Age  EstimatedSalary  Gender_Male
0     19            19000            1
1     35            20000            1
2     26            43000            0
3     27            57000            0
4     19            76000            1
..   ...              ...          ...
395   46            41000            0
396   51            23000            1
397   50            20000            0
398   36            33000            1
399   49            36000            0

[400 rows x 3 columns]

In [7]:
dep=dataset[['Purchased']]
dep

Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [8]:
dataset["Purchased"].value_counts()

0    257
1    143
Name: Purchased, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep,dep,test_size=1/3,random_state=0)
x_train,x_test,y_train,y_test


(     Age  EstimatedSalary  Gender_Male
 218   46            96000            0
 101   28            59000            1
 311   39            96000            1
 194   28            89000            1
 326   41            72000            1
 ..   ...              ...          ...
 323   48            30000            0
 192   29            43000            1
 117   36            52000            1
 47    27            54000            0
 172   26           118000            0
 
 [266 rows x 3 columns],      Age  EstimatedSalary  Gender_Male
 132   30            87000            1
 309   38            50000            0
 341   35            75000            1
 196   30            79000            0
 246   35            50000            0
 ..   ...              ...          ...
 168   29           148000            1
 150   26            15000            0
 393   60            42000            1
 66    24            19000            1
 240   42           149000            1
 
 [134 rows x

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [11]:
x_train,x_test

(array([[ 0.81203707,  0.7926083 , -0.99250926],
        [-0.96332069, -0.30625786,  1.00754728],
        [ 0.12162016,  0.7926083 ,  1.00754728],
        [-0.96332069,  0.5847147 ,  1.00754728],
        [ 0.31888214,  0.07983025,  1.00754728],
        [ 0.71340608, -1.28632769,  1.00754728],
        [-0.47016576, -0.00926701, -0.99250926],
        [-1.75236858,  0.3768211 , -0.99250926],
        [-0.66742773,  0.13922842,  1.00754728],
        [ 0.41751312,  0.31742293,  1.00754728],
        [-0.27290378,  0.07983025, -0.99250926],
        [-0.47016576,  2.36665983, -0.99250926],
        [ 0.22025115,  0.05013116,  1.00754728],
        [ 1.30519201,  2.27756258, -0.99250926],
        [ 0.81203707,  0.28772385,  1.00754728],
        [-0.27290378,  0.16892751,  1.00754728],
        [ 0.02298918, -0.54385055,  1.00754728],
        [-0.1742728 ,  0.16892751, -0.99250926],
        [-0.07564181,  0.25802476, -0.99250926],
        [ 0.02298918, -0.24685969,  1.00754728],
        [ 2.19287089

In [24]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
param_grid={'criterion':['gini','entropy'],
           'max_features':['auto','sqtr','log2'],
           'splitter':['best','random']}
grid=GridSearchCV(DecisionTreeClassifier(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid.fit(x_train,y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits


C:\Users\PC\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
20 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\PC\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\PC\Anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 942, in fit
    X_idx_sorted=X_idx_sorted,
  File "C:\Users\PC\Anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 282, in fit
    "Invalid value for max_features. "
ValueError: Invalid value for max_features. Allowed string val

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqtr', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [25]:
re=grid.cv_results_
grid_predictions=grid.predict(x_test)
grid_predictions


array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1], dtype=int64)

In [26]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_predictions)
print("Confusion Matrix:\n",cm)

Confusion Matrix:
 [[78  7]
 [ 8 41]]


In [28]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_predictions)
print("classification_report:\n",clf_report)

classification_report:
               precision    recall  f1-score   support

           0       0.91      0.92      0.91        85
           1       0.85      0.84      0.85        49

    accuracy                           0.89       134
   macro avg       0.88      0.88      0.88       134
weighted avg       0.89      0.89      0.89       134



In [29]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter{}:\n".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter{'criterion': 'gini', 'max_features': 'log2', 'splitter': 'best'}:
 0.88781000045891


In [30]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

0.8771908763505402

In [34]:
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.007540      0.003469         0.001602        0.000801   
1        0.003750      0.000757         0.001994        0.000892   
2        0.003601      0.000793         0.000000        0.000000   
3        0.003337      0.006157         0.000000        0.000000   
4        0.000000      0.000000         0.000000        0.000000   
5        0.006249      0.007653         0.000000        0.000000   
6        0.003121      0.006242         0.000000        0.000000   
7        0.000000      0.000000         0.003124        0.006248   
8        0.003125      0.006249         0.000000        0.000000   
9        0.003128      0.006255         0.000000        0.000000   
10       0.006249      0.007653         0.000000        0.000000   
11       0.000000      0.000000         0.003121        0.006242   

   param_criterion param_max_features param_splitter  \
0             gini               auto           best   
1             gini               auto         random   
2             gini               sqtr           best   
3             gini               sqtr         random   
4             gini               log2           best   
5             gini               log2         random   
6          entropy               auto           best   
7          entropy               auto         random   
8          entropy               sqtr           best   
9          entropy               sqtr         random   
10         entropy               log2           best   
11         entropy               log2         random   

                                               params  split0_test_score  \
0   {'criterion': 'gini', 'max_features': 'auto', ...           0.799620   
1   {'criterion': 'gini', 'max_features': 'auto', ...           0.847141   
2   {'criterion': 'gini', 'max_features': 'sqtr', ...                NaN   
3   {'criterion': 'gini', 'max_features': 'sqtr', ...                NaN   
4   {'criterion': 'gini', 'max_features': 'log2', ...           0.808927   
5   {'criterion': 'gini', 'max_features': 'log2', ...           0.808927   
6   {'criterion': 'entropy', 'max_features': 'auto...           0.826263   
7   {'criterion': 'entropy', 'max_features': 'auto...           0.770712   
8   {'criterion': 'entropy', 'max_features': 'sqtr...                NaN   
9   {'criterion': 'entropy', 'max_features': 'sqtr...                NaN   
10  {'criterion': 'entropy', 'max_features': 'log2...           0.847141   
11  {'criterion': 'entropy', 'max_features': 'log2...           0.808927   

    split1_test_score  split2_test_score  split3_test_score  \
0            0.852030           0.814409           0.832483   
1            0.793754           0.758030           0.813179   
2                 NaN                NaN                NaN   
3                 NaN                NaN                NaN   
4            0.907177           0.795256           0.886792   
5            0.773585           0.778067           0.905069   
6            0.828959           0.777291           0.906166   
7            0.815037           0.735849           0.793565   
8                 NaN                NaN                NaN   
9                 NaN                NaN                NaN   
10           0.888107           0.777291           0.851527   
11           0.852030           0.775815           0.885265   

    split4_test_score  mean_test_score  std_test_score  rank_test_score  
0            0.867097         0.833128        0.024433                4  
1            0.901744         0.822770        0.048900                6  
2                 NaN              NaN             NaN                9  
3                 NaN              NaN             NaN               10  
4            0.903610         0.860353        0.048260                1  
5            0.867097         0.826549        0.051528                5  
6            0.770530         0.821842        0.048577         

In [36]:
print(grid.best_params_)

{'criterion': 'gini', 'max_features': 'log2', 'splitter': 'best'}


In [37]:
age_input=float(input('Age input:'))
Salary_input=float(input('Salary:'))
gender_male_input=int(input("gender male 0 or 1:"))


Age input:40
Salary:100000
gender male 0 or 1:0


In [38]:
Future_prediction=grid.predict([[age_input,Salary_input,gender_male_input]])
print("Future_Prediction={}".format(Future_prediction))

Future_Prediction=[1]
