In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [3]:
dataset=pd.read_csv("Social_Network_Ads.csv")
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [7]:
dataset=dataset.drop("User ID",axis=1)
dataset

Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [8]:
dataset.columns

Index(['Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [10]:
indep=dataset[['Age', 'EstimatedSalary','Gender_Male']]
indep

Age  EstimatedSalary  Gender_Male
0     19            19000            1
1     35            20000            1
2     26            43000            0
3     27            57000            0
4     19            76000            1
..   ...              ...          ...
395   46            41000            0
396   51            23000            1
397   50            20000            0
398   36            33000            1
399   49            36000            0

[400 rows x 3 columns]

In [11]:
dep=dataset[['Purchased']]
dep

Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [14]:
dataset["Purchased"].value_counts()

0    257
1    143
Name: Purchased, dtype: int64

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep,dep,test_size=1/3,random_state=0)
x_train,x_test,y_train,y_test


(     Age  EstimatedSalary  Gender_Male
 218   46            96000            0
 101   28            59000            1
 311   39            96000            1
 194   28            89000            1
 326   41            72000            1
 ..   ...              ...          ...
 323   48            30000            0
 192   29            43000            1
 117   36            52000            1
 47    27            54000            0
 172   26           118000            0
 
 [266 rows x 3 columns],      Age  EstimatedSalary  Gender_Male
 132   30            87000            1
 309   38            50000            0
 341   35            75000            1
 196   30            79000            0
 246   35            50000            0
 ..   ...              ...          ...
 168   29           148000            1
 150   26            15000            0
 393   60            42000            1
 66    24            19000            1
 240   42           149000            1
 
 [134 rows x

In [16]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [19]:
x_train,x_test

(array([[ 0.81203707,  0.7926083 , -0.99250926],
        [-0.96332069, -0.30625786,  1.00754728],
        [ 0.12162016,  0.7926083 ,  1.00754728],
        [-0.96332069,  0.5847147 ,  1.00754728],
        [ 0.31888214,  0.07983025,  1.00754728],
        [ 0.71340608, -1.28632769,  1.00754728],
        [-0.47016576, -0.00926701, -0.99250926],
        [-1.75236858,  0.3768211 , -0.99250926],
        [-0.66742773,  0.13922842,  1.00754728],
        [ 0.41751312,  0.31742293,  1.00754728],
        [-0.27290378,  0.07983025, -0.99250926],
        [-0.47016576,  2.36665983, -0.99250926],
        [ 0.22025115,  0.05013116,  1.00754728],
        [ 1.30519201,  2.27756258, -0.99250926],
        [ 0.81203707,  0.28772385,  1.00754728],
        [-0.27290378,  0.16892751,  1.00754728],
        [ 0.02298918, -0.54385055,  1.00754728],
        [-0.1742728 ,  0.16892751, -0.99250926],
        [-0.07564181,  0.25802476, -0.99250926],
        [ 0.02298918, -0.24685969,  1.00754728],
        [ 2.19287089

In [26]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
param_grid={'kernel':['linear','rbf','poly','sigmoid'],
           'gamma':['auto','scale'],
           'C':[10,100,1000,2000,3000]}
grid=GridSearchCV(SVC(probability=True),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid.fit(x_train,y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits


C:\Users\PC\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GridSearchCV(estimator=SVC(probability=True), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['linear', 'rbf', 'poly', 'sigmoid']},
             scoring='f1_weighted', verbose=3)

In [28]:
re=grid.cv_results_
grid_predictions=grid.predict(x_test)
grid_predictions


array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 0], dtype=int64)

In [30]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_predictions)
print("Confusion Matrix:\n",cm)

Confusion Matrix:
 [[80  5]
 [ 7 42]]


In [31]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_predictions)
print("classification_report:\n",clf_report)

classification_report:
               precision    recall  f1-score   support

           0       0.92      0.94      0.93        85
           1       0.89      0.86      0.88        49

    accuracy                           0.91       134
   macro avg       0.91      0.90      0.90       134
weighted avg       0.91      0.91      0.91       134



In [32]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter{}:\n".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}:
 0.9100355779243318


In [34]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

0.9539015606242497

In [36]:
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0        0.115603  3.364939e-02         0.000000        0.000000      10   
1        0.028121  6.249548e-03         0.000000        0.000000      10   
2        0.031242  5.840039e-07         0.009373        0.007653      10   
3        0.024994  7.653020e-03         0.003124        0.006249      10   
4        0.031245  3.036820e-06         0.003126        0.006251      10   
5        0.031241  4.800213e-06         0.006247        0.007651      10   
6        0.031243  8.583069e-07         0.003125        0.006250      10   
7        0.018746  6.248522e-03         0.006250        0.007654      10   
8        0.118729  1.875476e-02         0.003124        0.006249     100   
9        0.034367  6.248761e-03         0.006249        0.007653     100   
10       0.140568  3.695707e-02         0.004119        0.006065     100   
11       0.024995  7.664471e-03         0.006247        0.007651     100   
12       0.109889  9.941901e-03         0.004294        0.006100     100   
13       0.037491  7.652826e-03         0.012497        0.006248     100   
14       0.167001  5.433572e-02         0.004277        0.002374     100   
15       0.027787  6.116303e-03         0.004106        0.006330     100   
16       0.436354  1.870266e-01         0.009082        0.007435    1000   
17       0.083559  3.690293e-02         0.005112        0.006514    1000   
18       0.544997  1.280742e-01         0.000798        0.000978    1000   
19       0.018657  6.072307e-03         0.000576        0.001152    1000   
20       0.509225  1.087643e-01         0.006648        0.007363    1000   
21       0.087441  2.589887e-02         0.010151        0.006720    1000   
22       0.723435  4.826826e-01         0.000997        0.001995    1000   
23       0.024997  4.970721e-03         0.006893        0.004708    1000   
24       0.906501  2.011833e-01         0.000000        0.000000    2000   
25       0.142928  4.066295e-02         0.002182        0.002693    2000   
26       1.267137  4.971891e-01         0.000399        0.000798    2000   
27       0.009373  7.652903e-03         0.006249        0.007653    2000   
28       0.954587  2.025662e-01         0.000000        0.000000    2000   
29       0.129283  3.844663e-02         0.007246        0.007077    2000   
30       1.208177  4.486356e-01         0.000399        0.000797    2000   
31       0.031244  9.882421e-03         0.000000        0.000000    2000   
32       1.059327  4.010005e-01         0.003124        0.006249    3000   
33       0.149598  5.115911e-02         0.007688        0.006798    3000   
34       1.504989  3.124289e-01         0.006249        0.007653    3000   
35       0.019016  2.822302e-03         0.003387        0.005023    3000   
36       1.204557  1.737932e-01         0.000000        0.000000    3000   
37       0.093728  7.260095e-02         0.003124        0.006248    3000   
38       1.112095  4.793851e-01         0.003124        0.006248    3000   
39       0.024994  7.651560e-03         0.003124        0.006249    3000   

   param_gamma param_kernel  \
0         auto       linear   
1         auto          rbf   
2         auto         poly   
3         auto      sigmoid   
4        scale       linear   
5        scale          rbf   
6        scale         poly   
7        scale      sigmoid   
8         auto       linear   
9         auto          rbf   
10        auto         poly   
11        auto      sigmoid   
12       scale       linear   
13       scale          rbf   
14       scale         poly   
15       scale      sigmoid   
16        auto       linear   
17        auto          rbf   
18        auto         poly   
19        auto      sigmoid   
20       scale       linear   
21       scale          rbf   
22       scale         poly   
23       scale      sigmoid   
24        auto       linear   
25        auto          rbf   
26        auto         poly   
27        auto     

In [38]:
print(grid.best_params_)

{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}


In [39]:
age_input=float(input('Age input:'))
Salary_input=float(input('Salary:'))
gender_male_input=int(input("gender male 0 or 1:"))


Age input:40
Salary:100000
gender male 0 or 1:0


In [49]:
Future_prediction=grid.predict([[age_input,Salary_input,gender_male_input]])
print("Future_Prediction={}".format(Future_prediction))

Future_Prediction=[1]
